### ISSUE TITLE
Touch move support

### ISSUE THREAD

**Issue by billcolumbia** [silvestreh/onScreen#15] opened 2014-06-03 16:33 UTC
I'm currently hacking on this now and trying to add support for ` .on({'touchmove' ` so that `doIn()` and other methods can be fired while scrolling on a touch device, instead of after the user stops scrolling. Were you thinking about implementing anything like this in the future? Thanks for a sweet tool, nonetheless :+1:

**Comment by silvestreh** [comment] 2016-05-06 05:13
It's been… well, years. But I'm closing this issue as the new OnScreen is completely different and, as far as I could test (I only own one Android device) it works as intended.

**Closed by silvestreh** 2016-05-06 05:13 UTC
Labels: enhancement

**Comment by billcolumbia** [comment] 2016-05-06 15:27
I was never able to get it working consistently back then. It seems it was added to both iOS Safari and Android browsers though 👍  thanks for the follow up!
